# Generated by Django 3.2.4 on 2021-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='downloads')),
                ('description', models.TextField(default='here is some description')),
            ],
        ),
    ]
